VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  #config.vm.box = "ubuntu/ubuntu-14.10-amd64"
  #config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "ubuntu/trusty64"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "ami" do |ami|
    ami.vm.network :private_network, :ip => "172.16.20.51"
    ami.vm.hostname = "ami"
    ami.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    ami.vm.provision "shell", inline: <<SCRIPT
#bash /vagrant/install.sh
SCRIPT
  end
end

begin
  load 'Vagrantfile.local'
rescue LoadError
end