# -*- mode: ruby -*-
# vi: set ft=ruby :

load '../aws_credentials.rb'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provider :aws do |aws, override|
    inject_aws_credentials(aws, override, "builderami")
    inject_aws_instance_name(aws, "amibuilder")
  end

  config.vm.define "ami" do |ami|
    ami.vm.hostname = "ami"
    ami.vm.provision "file", source: "../shared/etc/init/docker.io.conf", destination: "/tmp/dockerupstart.conf"
    ami.vm.provision "file", source: "../shared/etc/default/docker.io", destination: "/tmp/dockerdefaults"
    ami.vm.provision "file", source: "../shared/install.sh", destination: "/tmp/install.sh"
    ami.vm.provision "shell", inline: <<SCRIPT
bash /tmp/install.sh
SCRIPT
  end
end

begin
  load 'Vagrantfile.local'
rescue LoadError
end