# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$update_flocker_plugin = <<SCRIPT
cd /root/flocker-docker-plugin && git checkout master && git pull
SCRIPT

$install_keys = <<SCRIPT
cp /vagrant/insecure_private_key /root/.ssh/id_rsa
cp /vagrant/insecure_public_key /root/.ssh/id_rsa.pub
cat /vagrant/insecure_public_key >> /root/.ssh/authorized_keys
chmod 0600 /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
SCRIPT

$make_zpool = <<SCRIPT
#mkdir -p /var/opt/flocker2
#truncate --size 10G /var/opt/flocker2/pool-vdev
#zpool create flocker /var/opt/flocker2/pool-vdev
#zpool import -d /var/opt/flocker/pool-vdev flocker
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.box = "docker-plugins-demo-vagrant-ubuntu-v10"
  config.vm.box_url = "http://storage.googleapis.com/experiments-clusterhq/vagrant-boxes/flocker-ubuntu14.04-zfs-v10.box"

  config.vm.define "master" do |master|
    master.vm.network :private_network, :ip => "172.16.70.250"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |v|
      v.memory = 1536
    end
    master.vm.provision :shell, inline: $update_flocker_plugin + $install_keys + $make_zpool
    config.vm.provision "file", source: "../shared/runweave.sh", destination: "/tmp/runweave.sh"
  end

  config.vm.define "runner" do |runner|
    runner.vm.network :private_network, :ip => "172.16.70.251"
    runner.vm.hostname = "runner"
    runner.vm.provider "virtualbox" do |v|
      v.memory = 1536
    end
    runner.vm.provision :shell, inline: $update_flocker_plugin + $install_keys + $make_zpool
    config.vm.provision "file", source: "../shared/runweave.sh", destination: "/tmp/runweave.sh"
  end

end
