# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

load 'runner_scripts.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.box = "docker-plugins-demo-vagrant-ubuntu-v12"
  config.vm.box_url = "https://storage.googleapis.com/experiments-clusterhq/vagrant-boxes/flocker-ubuntu14.04-zfs-v12.box"
  
  config.vm.define "master" do |master|
    master.vm.network :private_network, :ip => "172.16.70.250"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |v|
      v.memory = 1536
    end

    master.vm.provision :shell, inline: $prepare_flocker + $install_keys
    
    master.vm.provision "file", source: "./bakedcerts/cluster.crt", destination: "/tmp/flocker_certs/cluster.crt"

    master.vm.provision "file", source: "./bakedcerts/09727403-45a3-4e50-99ac-4ab9f4a13a8a.crt", destination: "/tmp/flocker_certs/node.crt"
    master.vm.provision "file", source: "./bakedcerts/09727403-45a3-4e50-99ac-4ab9f4a13a8a.key", destination: "/tmp/flocker_certs/node.key"

    master.vm.provision "file", source: "./bakedcerts/control-172.16.70.250.crt", destination: "/tmp/flocker_certs/control-service.crt"
    master.vm.provision "file", source: "./bakedcerts/control-172.16.70.250.key", destination: "/tmp/flocker_certs/control-service.key"

    master.vm.provision "file", source: "./bakedcerts/172.16.70.250-plugin.crt", destination: "/tmp/flocker_certs/plugin.crt"
    master.vm.provision "file", source: "./bakedcerts/172.16.70.250-plugin.key", destination: "/tmp/flocker_certs/plugin.key"

    master.vm.provision "file", source: "./bakedcerts/agent.yml", destination: "/tmp/flocker_certs/agent.yml"
    
    master.vm.provision :shell, inline: $copy_certs + $flocker_control + $flocker_node + $flocker_plugin_master

    master.vm.provision "file", source: "../shared/runweave.sh", destination: "/tmp/runweave.sh"

    master.vm.provision "shell", inline: <<SCRIPT
bash /tmp/runweave.sh 10 172.16.70.251
#sleep 5
#docker network create -d weave demonet
#/vagrant/bin/swarm manage --host 0.0.0.0:2378 172.16.70.250:2375,172.16.70.251:2375 &
#bash /vagrant/run_proxy.sh
SCRIPT

  end

  config.vm.define "runner" do |runner|
    runner.vm.network :private_network, :ip => "172.16.70.251"
    runner.vm.hostname = "runner"
    runner.vm.provider "virtualbox" do |v|
      v.memory = 1536
    end

    runner.vm.provision :shell, inline: $prepare_flocker + $install_keys

    runner.vm.provision "file", source: "./bakedcerts/cluster.crt", destination: "/tmp/flocker_certs/cluster.crt"

    runner.vm.provision "file", source: "./bakedcerts/73b58895-4a6e-432a-8a85-44dfe756bc20.crt", destination: "/tmp/flocker_certs/node.crt"
    runner.vm.provision "file", source: "./bakedcerts/73b58895-4a6e-432a-8a85-44dfe756bc20.key", destination: "/tmp/flocker_certs/node.key"

    runner.vm.provision "file", source: "./bakedcerts/172.16.70.251-plugin.crt", destination: "/tmp/flocker_certs/plugin.crt"
    runner.vm.provision "file", source: "./bakedcerts/172.16.70.251-plugin.key", destination: "/tmp/flocker_certs/plugin.key"

    runner.vm.provision "file", source: "./bakedcerts/agent.yml", destination: "/tmp/flocker_certs/agent.yml"

    runner.vm.provision :shell, inline: $copy_certs + $flocker_node + $flocker_plugin_runner

    runner.vm.provision "file", source: "../shared/runweave.sh", destination: "/tmp/runweave.sh"

    runner.vm.provision "shell", inline: <<SCRIPT
bash /tmp/runweave.sh 11 172.16.70.250
#docker network create -d weave demonet
SCRIPT

  end

end
