# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
PROJECTS_HOME = ENV['PROJECTS_HOME'] || "../"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/ubuntu-14.10-amd64"
  config.vm.network :private_network, :ip => "172.16.100.100"
  config.vm.hostname = "node1"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
end