# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provider :aws do |aws, override|
    aws_config = YAML::load_file(File.join(File.dirname(__FILE__), "..", ".aws_secrets"))
    aws.access_key_id = aws_config.fetch("access_key_id")
    aws.secret_access_key = aws_config.fetch("secret_access_key")
    aws.keypair_name = aws_config.fetch("keypair_name")
    name = aws_config.fetch("instance_name_prefix") + " docker-plugins-ami-builder"
    aws.tags = {
        'Name' => name
    }
    aws.ami = "ami-3cf8b154"
    aws.instance_type = "c3.xlarge"

    override.vm.box = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "root"
    override.ssh.private_key_path = aws_config.fetch("keypair_path")
  end

  config.vm.define "compiler" do |compiler|
    compiler.vm.box = "ubuntu/ubuntu-14.10-amd64"
    compiler.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box"
    compiler.vm.network :private_network, :ip => "172.16.10.50"
    compiler.vm.hostname = "compiler"
    compiler.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
    load 'builder_scripts.rb'
    config.vm.synced_folder "./.build/docker", "/home/vagrant/src/github.com/docker/docker"
    config.vm.synced_folder "./.build/weave", "/home/vagrant/src/github.com/weaveworks/weave"

    config.vm.provision :docker, :images => [ "ubuntu:14.04", "gliderlabs/alpine:latest" ]

    config.vm.provision :shell, :inline => $install_build_deps
    config.vm.provision :shell, :inline => $tweak_user_env, :privileged => false
    config.vm.provision :shell, :inline => $tweak_docker_daemon
  end

  config.vm.define "ami" do |ami|
    ami.vm.box = "ubuntu/trusty64"
    ami.vm.network :private_network, :ip => "172.16.10.51"
    ami.vm.hostname = "ami"
    ami.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    ami.vm.provision "shell", inline: <<SCRIPT
bash /vagrant/install.sh
SCRIPT
  end
end

begin
  load 'Vagrantfile.local'
rescue LoadError
end