# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "compiler" do |compiler|
    compiler.vm.box = "ubuntu/ubuntu-14.10-amd64"
    compiler.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box"
    compiler.vm.network :private_network, :ip => "172.16.10.50"
    compiler.vm.hostname = "compiler"
    compiler.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
    load 'builder_scripts.rb'
    config.vm.synced_folder "./.build/docker", "/home/vagrant/src/github.com/docker/docker"
    config.vm.synced_folder "./.build/weave", "/home/vagrant/src/github.com/weaveworks/weave"

    config.vm.provision :docker, :images => [ "ubuntu:14.04", "gliderlabs/alpine:latest" ]

    config.vm.provision :shell, :inline => $install_build_deps
    config.vm.provision :shell, :inline => $tweak_user_env, :privileged => false
    config.vm.provision :shell, :inline => $tweak_docker_daemon
  end

end

begin
  load 'Vagrantfile.local'
rescue LoadError
end