# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# there are runner_vms + 1 nodes (because there is also a master)
$runner_vms = 2

load '../aws_credentials.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.provider :aws do |aws, override|
    inject_aws_credentials(aws, override, "runnerami")
  end

  vms = (1..$runner_vms).map{ |a| "runner-#{a}" } << 'master'

  vms.each_with_index do |i, x|
    config.vm.define vm_name = i do |config|
      config.vm.provider :aws do |aws, override|
        inject_aws_instance_name(aws, i)
      end

      config.vm.hostname = vm_name

      if vm_name == 'master'
        config.vm.provision "shell", inline: <<SCRIPT
echo master > /tmp/file.txt
SCRIPT
      end

      config.vm.provision "shell", inline: <<SCRIPT
# get around why the docker.sock was not working nicely
service docker restart
SCRIPT

    end
  end
end

begin
  load 'Vagrantfile.local'
rescue LoadError
end